-- =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
-- SECURITY POLICY: Platform.TenantIsolation
-- Purpose: Isolation layer 3 (Row-Level Security) on every table with a TenantId: the filter hides another tenant's
--          rows from reads, updates and deletes, and the block predicates refuse to insert a row for another tenant or
--          to move one there. The rule is Platform.TenantAccess. A new tenant table must be added here;
--          RowLevelSecurityTests fails otherwise.
-- Author: Courier team
-- Date: 2026-10-04
-- =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
CREATE SECURITY POLICY [Platform].[TenantIsolation]
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Delivery].[DeliveryAttempt],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Delivery].[DeliveryAttempt] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Delivery].[DeliveryAttempt] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Delivery].[DeliveryRun],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Delivery].[DeliveryRun] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Delivery].[DeliveryRun] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Delivery].[PickupRequest],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Delivery].[PickupRequest] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Delivery].[PickupRequest] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Delivery].[ReturnList],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Delivery].[ReturnList] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Delivery].[ReturnList] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Delivery].[ReturnListParcel],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Delivery].[ReturnListParcel] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Delivery].[ReturnListParcel] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Delivery].[Rider],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Delivery].[Rider] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Delivery].[Rider] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Delivery].[VehicleCapacity],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Delivery].[VehicleCapacity] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Delivery].[VehicleCapacity] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Identity].[User],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Identity].[User] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Identity].[User] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Merchants].[Merchant],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Merchants].[Merchant] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Merchants].[Merchant] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Merchants].[MerchantApiKey],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Merchants].[MerchantApiKey] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Merchants].[MerchantApiKey] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Merchants].[MerchantPicture],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Merchants].[MerchantPicture] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Merchants].[MerchantPicture] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Merchants].[MerchantPayoutAccount],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Merchants].[MerchantPayoutAccount] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Merchants].[MerchantPayoutAccount] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Merchants].[Moderator],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Merchants].[Moderator] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Merchants].[Moderator] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Merchants].[PickupPoint],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Merchants].[PickupPoint] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Merchants].[PickupPoint] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Network].[Area],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Network].[Area] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Network].[Area] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Network].[Hub],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Network].[Hub] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Network].[Hub] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Network].[Zone],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Network].[Zone] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Network].[Zone] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Notifications].[OutboxMessage],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Notifications].[OutboxMessage] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Notifications].[OutboxMessage] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Parcels].[Parcel],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Parcels].[Parcel] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Parcels].[Parcel] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Parcels].[ParcelEvent],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Parcels].[ParcelEvent] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Parcels].[ParcelEvent] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Parcels].[ParcelRequest],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Parcels].[ParcelRequest] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Parcels].[ParcelRequest] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Payments].[LedgerEntry],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Payments].[LedgerEntry] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Payments].[LedgerEntry] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Payments].[OnlinePayment],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Payments].[OnlinePayment] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Payments].[OnlinePayment] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Payments].[Payout],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Payments].[Payout] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Payments].[Payout] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Pricing].[DeliveryRate],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Pricing].[DeliveryRate] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Pricing].[DeliveryRate] AFTER UPDATE
WITH (STATE = ON, SCHEMABINDING = ON);
