-- =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
-- SECURITY POLICY: Platform.TenantIsolation
-- Purpose: Isolation layer 3 (Row-Level Security) on every table with a TenantId: the filter hides another tenant's
--          rows from reads, updates and deletes, and the block predicates refuse to insert a row for another tenant or
--          to move one there. The rule is Platform.TenantAccess. A new tenant table must be added here;
--          RowLevelSecurityTests fails otherwise.
-- Author: Courier team
-- Date: 2026-09-30
-- =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
CREATE SECURITY POLICY [Platform].[TenantIsolation]
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Customers].[Customer],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Customers].[Customer] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Customers].[Customer] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Customers].[CustomerAddress],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Customers].[CustomerAddress] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Customers].[CustomerAddress] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Customers].[PhoneOtp],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Customers].[PhoneOtp] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Customers].[PhoneOtp] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Delivery].[Rider],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Delivery].[Rider] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Delivery].[Rider] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Delivery].[Trip],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Delivery].[Trip] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Delivery].[Trip] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Delivery].[TripStop],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Delivery].[TripStop] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Delivery].[TripStop] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Grouping].[DeliveryGroup],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Grouping].[DeliveryGroup] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Grouping].[DeliveryGroup] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Identity].[User],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Identity].[User] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Identity].[User] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Merchants].[Merchant],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Merchants].[Merchant] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Merchants].[Merchant] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Merchants].[MerchantApiKey],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Merchants].[MerchantApiKey] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Merchants].[MerchantApiKey] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Merchants].[PickupPoint],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Merchants].[PickupPoint] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Merchants].[PickupPoint] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Network].[Area],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Network].[Area] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Network].[Area] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Network].[Hub],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Network].[Hub] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Network].[Hub] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Network].[PickupRoute],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Network].[PickupRoute] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Network].[PickupRoute] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Network].[Zone],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Network].[Zone] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Network].[Zone] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Notifications].[OutboxMessage],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Notifications].[OutboxMessage] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Notifications].[OutboxMessage] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Orders].[Order],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Orders].[Order] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Orders].[Order] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Orders].[OrderStatusHistory],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Orders].[OrderStatusHistory] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Orders].[OrderStatusHistory] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Orders].[Package],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Orders].[Package] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Orders].[Package] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Payments].[LedgerEntry],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Payments].[LedgerEntry] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Payments].[LedgerEntry] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Payments].[Payment],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Payments].[Payment] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Payments].[Payment] AFTER UPDATE,
    ADD FILTER PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Payments].[Settlement],
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Payments].[Settlement] AFTER INSERT,
    ADD BLOCK PREDICATE [Platform].[TenantAccess]([TenantId]) ON [Payments].[Settlement] AFTER UPDATE
WITH (STATE = ON, SCHEMABINDING = ON);
